const lan = {
  fr: {
    findCraftman: "Trouver un artisan",
    orderTracking: "Suivi de commande",
    espace: "MON ESPACE ARTISAN / ATELIER",
    search: "Rechercher",
    order: "Commande",
    noResults:
      "Nous n'avons pas encore d'artisan dans cette catégorie.Bientôt restez connecté.",
    aboutUs: "A propos de nous",
    contactUs: "Nous contacter",
    email: "Email",
    emailAdress: "Adresse e-mail",
    password: "Mot de passe",
    phone: "Téléphone",
    whatsapp: "Whatsapp",
    country: "Pays",
    town: "Ville",
    accounts: "Compte",
    logout: "Déconnexion",
    deleteAccount: "Supprimer mon compte",
    whoWeAre: "Qui sommes nous ?",
    ourStories:
      "CEEDOW est une plateforme de mise en lumière du savoir-faire et des talents de l’artisanat à destination de particuliers ou professionnels souhaitant confectionner des articles de mode.",
    storydetail:
      "Les professionnels du secteur de l'art et de la mode pourront ainsi donner une dimension éco-responsable à leurs futures collections.",
    storydetail2:
      "C’est la confiance instaurée d’un bout à l’autre de la chaîne de production de part notre proposition innovante.",
    storydetail3:
      "C’est également la volonté de connecter l’expertise de nos artisans à nos clients.",
    mission: " Quelle est notre mission ?",
    mission1:
      "Notre mission est de mettre en relation des clients avec des artisans qualifiés. C’est permettre à des artisans d’acquérir de nouveaux marchés aussi bien intérieurs qu'extérieurs.",
    mission2:
      " Aux amateurs d’art et de mode, nous leur permettons de trouver des prestataires spécialisés dans ce domaine capable de",
    mission3:
      " Ensemble contribuons à la création de la visibilité et à la construction de l'identité digitale de nos artisans.",
    join: "Rejoindre Ceedow",
    send: "Envoyer",
    lastName: "Prénom",
    name: "Prénom/Nom",
    firstName: "Nom",
    object: "Objet",
    passwordInformation:
      "Le mot de passe doit comporter au moins 6 caractères.",
    emailInformation: "Veuillez entrer un adresse email valide.",
    continue: "Continuer",
    sigin: "Connexion",
    singup: "S'inscrire",
    noAccountInfo: "Vous n'avez pas créé de compte ?",
    haveAccount: "Vous avez déjà un compte ?",
    continueWiathApple: "Continuer via Apple",
    continueWiathGoogle: "Continuer via Google",
    continueWiathFacebook: "Continuer via Facebook",
    continueWiathEmail: "Continuer via your votre email",
    continueNoAccount: "Continuer sans compte",
    ceedow: "Ceedow",
    setPassword: "Définir un mot de passe",
    artisanChoiceType: "Quel type d'artisan recherche tu ?",
    createMyAccount: "Créer mon compte",
    return: "Retour",
    backDropWait: "Veuillez patienter...",
    duplicatedEmail:"Cette adresse email est déjà prise, veuillez utiliser une autre.",
    defaultError: "Une erreur est produite, alors veuillez réessayer s'il vous plait !!!",
    verifyAllField: "Veuillez verifier tous les champs"
  },
  en: {
    findCraftman: "Find craftsman",
    orderTracking: "Order tracking",
    espace: "MY ARTISAN / WORKSHOP SPACE",
    search: "Search",
    order: "Order",
    noResults:
      "We don't have any craftsman in this category yet.Soon, Stay connected",
    aboutUs: "About Us",
    contactUs: "Contact Us",
    email: "Email",
    phone: "Phone number",
    whatsapp: "Whatsapp",
    country: "Country",
    town: "Town",
    accounts: "Accounts",
    logout: "Logout",
    deleteAccount: "Delete my account",
    whoWeAre: "About Us",
    ourStories:
      "CEEDOW is a platform highlighting craftsmanship and talents for individuals or professionals wanting to make fashion pieces.",
    storydetail:
      "Professionals in the art and fashion sector will thus be able to give an eco-responsible dimension to their future collections.",
    storydetail2:
      "It is the trust built from on end of the production chain to the other through our innovative proposition.",
    storydetail3:
      "It is also the desire to connect the expertise of our craftsmen to our customers.",
    mission: "What is our mission ?",
    mission1:
      "We aim is to connect customers with skilled craftsmen.It is to enable artisans to reach new markets, both domestic and foreign.",
    mission2:
      "We allow art and fashion lovers to work with service providers specializing in this field and capable of",
    mission3:
      "Together, let’s bring awareness and visibility to our artisans to help in the making of their digital identity.",
    join: "Join Ceedow",
    send: "Send",
    lastName: "LastName/FirstName",
    name: "LastName/FirstName",
    firstName: "FirstName",
    object: "Object",
    emailAdress: "E-mail address",
    password: "Password",
    passwordInformation: "The password must contain at least 6 characters.",
    emailInformation: "Please enter a valid email address.",
    continue: "Continue",
    sigin: "Sigin",
    singup: "Singup",
    noAccountInfo: "You haven't created an account?",
    haveAccount: "Already have an account ?",
    continueWiathApple: "Continue with Apple",
    continueWiathGoogle: "Continue with Google",
    continueWiathFacebook: "Continue with Facebook",
    continueWiathEmail: "Continue with your email",
    continueNoAccount: "Continue without account",
    ceedow: "Ceedow",
    setPassword: "Set password",
    artisanChoiceType: "Quel type d'artisan recherche tu ?",
    createMyAccount: "Create my account",
    return: "Return",
    backDropWait: "Please wait...",
    duplicatedEmail:"This email address is already taken, please use another one.",
    defaultError:"An error occurred, so please try again !!!",
    verifyAllField: "Please verify all fields"
  },
};
export default lan;
